CREATE TABLE [stage].[WellCareCentauri_20170424]
(
[Client_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_HICN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Medical_Record_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_Last_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_DOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_NPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Last_Name] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Specialty] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_Address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_City] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_Fax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Group_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Group_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor_Fax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chase_Priority] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Relations_Rep] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diagnosis_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD9_ICD10_Ind] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_FROM_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_To_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTRACT_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINE_OF_BUSINESS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chase_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddress] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceAddress] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceZIP] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressUsed] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOB] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneUSed] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAXUSed] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvancePhone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceFax] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewPhone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewFAX] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewOld] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneKey] [int] NULL,
[NewPhoneMerged] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewFAxMerged] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPIPhoneMerged] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPIFAXMerged] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentuariProviderID] [bigint] NULL,
[Member_PK] [bigint] NULL,
[Provider_PK] [bigint] NULL,
[ProviderMaster_PK] [bigint] NULL,
[ProviderOffice_PK] [bigint] NULL,
[NewProviderLastName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewProviderFirstName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriLocationID] [int] NULL,
[Used] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MergeProviderOfficePK] [int] NULL,
[MergeProviderGroup] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewProvider_PK] [int] NULL,
[NewProviderOffice_PK] [int] NULL,
[NewUSed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
